apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-backstage
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-backstage
spec:
  type: deployment-config
  owner: mattjmorrison-homelab
  lifecycle: experimental
  system: backstage
