apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: backstage
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: homelab/k8s-backstage/github-app-id
        property: value
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: homelab/k8s-backstage/github-app-client-id
        property: value
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: homelab/k8s-backstage/github-app-client-secret
        property: value
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: homelab/k8s-backstage/github-app-private-key
        property: value
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: homelab/k8s-backstage/backend-auth-key
        property: value
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: homelab/k8s-backstage/postgres-password
        property: value
