apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-zot-pull-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: backstage-zot-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{`{"auths":{"registry.morrisons.site":{"username":"k8s-backstage","password":"{{ .password }}","auth":"{{ printf "k8s-backstage:%s" .password | b64enc }}"}}}`}}
  data:
    - secretKey: password
      remoteRef:
        key: homelab/service/k8s-zot/k8s-backstage/zot-pull
        property: value
